import { createClient } from "@/lib/supabase/server";
import PDFDocument from "pdfkit";

export async function GET(
  _req: Request,
  { params }: { params: { id: string } }
) {
  const supabase = await createClient();

  const { data: userData } = await supabase.auth.getUser();
  if (!userData.user) {
    return new Response(JSON.stringify({ error: "Unauthorized" }), {
      status: 401,
      headers: { "Content-Type": "application/json" },
    });
  }

  const { data: invoice, error } = await supabase
    .from("invoices")
    .select("*")
    .eq("id", params.id)
    .eq("user_id", userData.user.id)
    .single();

  if (error || !invoice) {
    return new Response(JSON.stringify({ error: "Not found" }), {
      status: 404,
      headers: { "Content-Type": "application/json" },
    });
  }

  const { data: payments } = await supabase
    .from("payments")
    .select("amount, paid_at, method, notes, created_at")
    .eq("invoice_id", params.id)
    .eq("user_id", userData.user.id)
    .order("created_at", { ascending: true });

  const paymentsTotal =
    (payments || []).reduce((sum, p) => sum + Number(p.amount || 0), 0) || 0;

  const total = Number(invoice.total || 0);
  const deposit = Number(invoice.deposit || 0);
  const balance = Number(invoice.balance || 0);

  // Create PDF buffer in-memory
  const doc = new PDFDocument({ size: "A4", margin: 50 });
  const chunks: Uint8Array[] = [];

  doc.on("data", (chunk: Uint8Array) => chunks.push(chunk));
  const done = new Promise<Uint8Array>((resolve) => {
    doc.on("end", () => {
      // Concatenate Uint8Arrays
      const totalLength = chunks.reduce((sum, c) => sum + c.length, 0);
      const merged = new Uint8Array(totalLength);
      let offset = 0;
      for (const c of chunks) {
        merged.set(c, offset);
        offset += c.length;
      }
      resolve(merged);
    });
  });

  const money = (n: number) => `£${Number(n || 0).toFixed(2)}`;

  // Header
  doc.fontSize(20).fillColor("#000").text("MKR Control Hub", { align: "left" });
  doc.fontSize(11).fillColor("#555").text("Invoice", { align: "left" });
  doc.moveDown(1);
  doc.fillColor("#000");

  // Details
  doc.fontSize(14).text(`Invoice Ref: ${invoice.ref}`);
  doc.fontSize(11).text(`Client: ${invoice.client_name}`);
  doc.fontSize(11).text(`Event Date: ${invoice.event_date ?? "-"}`);
  doc.fontSize(11).text(`Status: ${invoice.status ?? "Draft"}`);

  doc.moveDown(1);

  // Summary
  doc.fontSize(12).text("Summary", { underline: true });
  doc.moveDown(0.5);

  doc.fontSize(11).text(`Total: ${money(total)}`);
  doc.fontSize(11).text(`Deposit: ${money(deposit)}`);
  doc.fontSize(11).text(`Payments: ${money(paymentsTotal)}`);

  doc.moveDown(0.25);
  doc.strokeColor("#eaeaea").moveTo(50, doc.y).lineTo(545, doc.y).stroke();
  doc.moveDown(0.25);

  doc.fontSize(12).text(`Balance Due: ${money(balance)}`);

  // Notes
  if (invoice.notes) {
    doc.moveDown(1);
    doc.fontSize(12).text("Notes", { underline: true });
    doc.moveDown(0.4);
    doc.fontSize(11).text(String(invoice.notes));
  }

  // Payments list
  doc.moveDown(1);
  doc.fontSize(12).text("Payments", { underline: true });
  doc.moveDown(0.4);

  if (!payments?.length) {
    doc.fontSize(11).fillColor("#555").text("No payments recorded.");
    doc.fillColor("#000");
  } else {
    payments.forEach((p, idx) => {
      const labelParts: string[] = [];
      if (p.paid_at) labelParts.push(`Date: ${p.paid_at}`);
      if (p.method) labelParts.push(`Method: ${p.method}`);
      const label = labelParts.length ? `(${labelParts.join(" • ")})` : "";

      doc
        .fontSize(11)
        .fillColor("#000")
        .text(`${idx + 1}. ${money(Number(p.amount || 0))} ${label}`);

      if (p.notes) {
        doc.fontSize(10).fillColor("#555").text(`   ${p.notes}`);
      }

      doc.moveDown(0.2);
    });
  }

  // Footer
  doc.moveDown(2);
  doc
    .fontSize(9)
    .fillColor("#777")
    .text(
      "Generated by MKR Control Hub • Please keep this invoice for your records.",
      { align: "center" }
    );

  doc.end();

  const pdfBytes = await done;

  return new Response(pdfBytes, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="invoice-${invoice.ref}.pdf"`,
      "Cache-Control": "no-store",
    },
  });
}
